In [1]:
import pyaudio
import struct
import math
import numpy as np
import time
from tkinter import TclError
from scipy.fftpack import fft
import matplotlib.pyplot as plt
import wave
%matplotlib tk

%matplotlib tk
%matplotlib tk

CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100
SHORT_NORMALIZE = (1.0/32768.0)


In [108]:
#testing mic
chunk = 1024      # Each chunk will consist of 1024 samples
sample_format = pyaudio.paInt16      # 16 bits per sample
channels = 1      # Number of audio channels
fs = 44100        # Record at 44100 samples per second
time_in_seconds = 3
filename = "soundsample.wav"
 
p = pyaudio.PyAudio()  # Create an interface to PortAudio
 
print('-----Now Recording-----')
 
#Open a Stream with the values we just defined
stream = p.open(format=sample_format,
                channels = channels,
                rate = fs,
                frames_per_buffer = chunk,
                input = True)
 
frames = []  # Initialize array to store frames
 
# Store data in chunks for 3 seconds
for i in range(0, int(fs / chunk * time_in_seconds)):
    data = stream.read(chunk)
    frames.append(data)
 
# Stop and close the Stream and PyAudio
stream.stop_stream()
stream.close()
p.terminate()
 
print('-----Finished Recording-----')
 
# Open and Set the data of the WAV file
file = wave.open(filename, 'wb')
file.setnchannels(channels)
file.setsampwidth(p.get_sample_size(sample_format))
file.setframerate(fs)
 
#Write and Close the File
file.writeframes(b''.join(frames))
file.close()

-----Now Recording-----
-----Finished Recording-----


In [2]:
def array_std(arr):
    return (arr-min(arr))/(max(arr)-min(arr))

In [3]:
def rms(frame):
        count = len(frame) / 2
        format = "%dh" % (count)
        shorts = struct.unpack(format, frame)

        sum_squares = 0.0
        for sample in shorts:
            n = sample * SHORT_NORMALIZE
            sum_squares += n * n
        rms = math.pow(sum_squares / count, 0.5)

        return rms * 1000

In [134]:
#testing out the output

p = pyaudio.PyAudio()
stream =p.open(
    format=FORMAT,
    channels= CHANNELS,
    rate=RATE,
    input=True,
    output=True,
    frames_per_buffer=CHUNK
)

# data = stream.read(CHUNK)
# data_int=struct.unpack(str(2*CHUNK)+ 'B',data)
# data_np = np.array(data_int, dtype='b')[::2] + 128
# data_np

test_data = []
for x in range(200):
    data = stream.read(CHUNK)
    max_inten =200
    intensity = int(rms(data)/7)
    if(intensity>30):
        intensity=30
    
#     data_int = struct.unpack(str(2 * CHUNK) + 'B', data)
#     data_np = np.array(data_int, dtype='b')[::2]+128
#     intensity=np.sum(array_std(data_np))
#     intensity=int((intensity/512)*30)
#     data_fft=fft(data_int)
#     abs_data = np.abs(data_fft[0:CHUNK])/(128*CHUNK)
#     added_data=[]
#     start=200
#     fin=220
#     for i in range(30):
#         added_data.append(np.sum(abs_data[start:fin]))
#         start+=20
#         fin+=20
#     color_arr=np.round_(((added_data-min(added_data))/(max(added_data)-min(added_data)))*255)
#     color_arr_int=[int(x) for x in color_arr]
#     color_str= ' '.join(map(str,color_arr_int))
#     color_str+=' p'
    test_data.append(intensity)
    
print(max(test_data))
test_data


29


[7,
 7,
 6,
 6,
 7,
 6,
 5,
 5,
 4,
 3,
 3,
 3,
 3,
 3,
 2,
 3,
 3,
 2,
 2,
 2,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 9,
 9,
 9,
 9,
 8,
 18,
 24,
 19,
 19,
 12,
 9,
 10,
 9,
 10,
 10,
 9,
 11,
 9,
 10,
 11,
 9,
 10,
 9,
 9,
 9,
 8,
 10,
 7,
 6,
 8,
 9,
 8,
 8,
 9,
 8,
 8,
 9,
 9,
 9,
 7,
 10,
 9,
 4,
 6,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 3,
 3,
 5,
 7,
 15,
 29,
 20,
 18,
 21,
 21,
 20,
 20,
 18,
 20,
 19,
 20,
 20,
 20,
 20,
 19,
 18,
 14,
 14,
 13,
 14,
 14,
 14,
 13,
 14,
 12,
 13,
 12,
 12,
 12,
 11,
 11,
 11,
 11,
 12,
 12,
 9,
 12,
 13,
 12,
 11,
 10,
 8,
 4,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 6,
 27,
 17,
 8,
 6,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 4,
 4,
 4]

In [75]:
# create matplotlib figure and axes
fig, (ax1, ax2) = plt.subplots(2, figsize=(15, 7))

# pyaudio class instance
p = pyaudio.PyAudio()

# stream object to get data from microphone
stream = p.open(
    format=FORMAT,
    channels=CHANNELS,
    rate=RATE,
    input=True,
    output=True,
    frames_per_buffer=CHUNK
)

# variable for plotting
x = np.arange(0, 2 * CHUNK, 2)       # samples (waveform)
xf = np.linspace(0, RATE, CHUNK)     # frequencies (spectrum)

# create a line object with random data
line, = ax1.plot(x, np.random.rand(CHUNK), '-', lw=2)

# create semilogx line for spectrum
line_fft, = ax2.semilogx(xf, np.random.rand(CHUNK), '-', lw=2)

# format waveform axes
ax1.set_title('AUDIO WAVEFORM')
ax1.set_xlabel('samples')
ax1.set_ylabel('volume')
ax1.set_ylim(0, 255)
ax1.set_xlim(0, 2 * CHUNK)
plt.setp(ax1, xticks=[0, CHUNK, 2 * CHUNK], yticks=[0, 128, 255])

# format spectrum axes
ax2.set_xlim(20, RATE / 2)

print('stream started')

# for measuring frame rate
frame_count = 0
start_time = time.time()

while True:
    
    # binary data
    data = stream.read(CHUNK)  
    
    # convert data to integers, make np array, then offset it by 127
    data_int = struct.unpack(str(2 * CHUNK) + 'B', data)
    
    # create np array and offset by 128
    data_np = np.array(data_int, dtype='b')[::2] + 128
    
    line.set_ydata(data_np)
    
    # compute FFT and update line
    yf = fft(data_int)
    line_fft.set_ydata(np.abs(yf[0:CHUNK])  / (128 * CHUNK))
    
    # update figure canvas
    try:
        fig.canvas.draw()
        fig.canvas.flush_events()
        frame_count += 1
        
    except TclError:
        
        # calculate average frame rate
        frame_rate = frame_count / (time.time() - start_time)
        
        print('stream stopped')
        print('average frame rate = {:.0f} FPS'.format(frame_rate))
        break

stream started
stream stopped
average frame rate = 8 FPS


In [22]:
import serial
ser = serial.Serial('/dev/ttyUSB0')
print(ser.name)
ser.write(b'a')
ser.close()

/dev/ttyUSB0


In [30]:
with serial.Serial('/dev/ttyUSB0',9600,timeout=3) as ser:
    ser.write(b'b')
    print(ser.readlines())
ser.close()

[]


In [3]:
import numpy as np
def randColo():
    random_mat = np.random.randint(1,10,size=(30))
    random_string = ' '.join(map(str,random_mat))
    random_string += ' p'
    return random_string

print(randColo())

4 1 7 2 9 4 1 4 7 3 2 7 6 6 1 4 8 2 8 6 9 3 6 4 3 5 6 9 5 8 p


In [10]:
# Importing Libraries
p = pyaudio.PyAudio()
stream =p.open(
    format=FORMAT,
    channels= CHANNELS,
    rate=RATE,
    input=True,
    output=True,
    frames_per_buffer=CHUNK
)
import serial
import time
arduino = serial.Serial(port='/dev/ttyUSB0', baudrate=9600, timeout=.1)
def write_read(x):
    arduino.write(bytes(x, 'utf-8'))
#     data = arduino.readlines()
#     return data
# while True:
#     num = input("Enter a number: ") # Taking input from user
    
#     value = write_read(num)
#     print(value) # printing the value
#     if num == 'r':
#         break
while True:
    data = stream.read(CHUNK)
    max_inten =200
    intensity = int(rms(data)/6)
    if(intensity>30):
        intensity=30
    intensity_str=str(intensity) + ' p'
    write_read(str(intensity_str))

KeyboardInterrupt: 

In [16]:
import numpy as np
random_mat = np.random.randint(1,10,size=(10,3))
fac=9
for i in range(10):
    random_mat[i] = random_mat[i]*fac
    fac=fac+2
print(random_mat)

[[ 63  81  54]
 [ 33  11  77]
 [ 91  78  13]
 [ 90  15  75]
 [ 17 119  34]
 [171  76  76]
 [105 168 105]
 [115 207 115]
 [ 50 200  50]
 [243 162 216]]
